### ISSUE TITLE
Upload logs artifact name contains invalid characters.

### ISSUE THREAD

**Issue by myrrc** [awalsh128/cache-apt-pkgs-action#89]
`Artifact name is not valid: libgtk-3-dev:amd64%Linux-amd64. Contains the following character:  Colon :`

Basically, a Linux package is of form "package-name:package-arch", e.g. g++:i386. Currently this action doesn't support such packages.

I assume the issue is here
https://github.com/awalsh128/cache-apt-pkgs-action/blob/9b2b4f2004c400ca4db1cd3622055dd784244fcb/action.yml#L79

**Comment by awalsh128** [comment]
Added regressions for this on the CI.
https://github.com/awalsh128/cache-apt-pkgs-action-ci/commit/0ba1888a97654d263795bf7da3bb28b311ffd92a
https://github.com/awalsh128/cache-apt-pkgs-action-ci/commit/2713b7ba166d7f4be0eca82a2be2ec1dd83aa03d

I think I may just use the CACHE_KEY instead since it will have only valid characters in any situation.

**Comment by awalsh128** [comment]
Looks like this fixed the issue.

Before https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/4090481445/jobs/7053925989
After https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/4090501587/jobs/7053958765

Will roll this up in my next patch once I address #84.

**Comment by awalsh128** [comment]
All set https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.2.4
